[project]
name = "fastl2lir"
version = "0.10"
description = "Fast L2-reguralized linear regression"
readme = "README.md"
authors = [
    { name = "Kei Majima", email = "kamitanilab@gmail.com" }
]
maintainers = [
    { name = "Shuntaro C. Aoki", email = "kamitanilab@gmail.com" },
    { name = "Yoshihiro Nagano", email = "kamitanilab@gmail.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.1"
dependencies = [
    "numpy>=1.16.6",
    "threadpoolctl>=2.1.0 ; python_full_version >= '3.5'",
    "tqdm>=4.64.1",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=4.6.11",
    "ruff>=0.0.17",
]
