[project]
name = "fastl2lir"
version = "0.11"
description = "Fast L2-reguralized linear regression"
readme = "README.md"
authors = [
    { name = "Kei Majima", email = "kamitanilab@gmail.com" }
]
maintainers = [
    { name = "Shuntaro C. Aoki", email = "kamitanilab@gmail.com" },
    { name = "Yoshihiro Nagano", email = "kamitanilab@gmail.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.22.0",
    "threadpoolctl>=2.1.0",
    "tqdm>=4.64.1",
]
[project.urls]
Homepage = "https://github.com/KamitaniLab/PyFastL2LiR"
Repository = "https://github.com/KamitaniLab/PyFastL2LiR"
"Bug Tracker" = "https://github.com/KamitaniLab/PyFastL2LiR/issues"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=4.6.11",
    "ruff>=0.0.17",
]
